2025-08-21 09:29:20,625 - ERROR - Erro SQLAlchemy ao buscar Responsaveis:
2025-08-21 09:31:09,105 - ERROR - Erro SQLAlchemy ao buscar Responsaveis:
	Traceback (most recent call last):
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2522, in get_property
	    return self._props[key]
	           ~~~~~~~~~~~^^^^^
	KeyError: 'finalizacao'
	
	The above exception was the direct cause of the following exception:
	
	Traceback (most recent call last):
	  File "/home/davi/Downloads/keyControlApi/resources/ResponsavelResource.py", line 17, in get
	    responsaveis = db.session.execute(query).scalars().all()
	                   ^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 779, in execute
	    return self._proxied.execute(
	           ^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
	    return self._execute_internal(
	           ^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
	    result: Result[Any] = compile_state_cls.orm_execute_statement(
	                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
	    result = conn.execute(
	             ^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
	    return meth(
	           ^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
	    return connection._execute_clauseelement(
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1629, in _execute_clauseelement
	    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
	                                                ^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 711, in _compile_w_cache
	    compiled_sql = self._compiler(
	                   ^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 320, in _compiler
	    return dialect.statement_compiler(dialect, self, **kw)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1446, in __init__
	    Compiled.__init__(self, dialect, statement, **kwargs)
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 886, in __init__
	    self.string = self.process(self.statement, **compile_kwargs)
	                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 932, in process
	    return obj._compiler_dispatch(self, **kwargs)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
	    return meth(self, **kw)  # type: ignore  # noqa: E501
	           ^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4728, in visit_select
	    compile_state = select_stmt._compile_state_factory(
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 687, in create_for_statement
	    return klass.create_for_statement(statement, compiler, **kw)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 447, in create_for_statement
	    return cls._create_orm_context(
	           ^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1175, in _create_orm_context
	    _QueryEntity.to_compile_state(
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2628, in to_compile_state
	    _MapperEntity(
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2708, in __init__
	    entity._post_inspect
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1338, in __get__
	    obj.__dict__[self.__name__] = result = self.fget(obj)
	                                           ^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2724, in _post_inspect
	    self._check_configure()
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2401, in _check_configure
	    _configure_registries({self.registry}, cascade=True)
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4214, in _configure_registries
	    _do_configure_registries(registries, cascade)
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4251, in _do_configure_registries
	    raise e
	sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Finalizar(finalizacao)]'. Original exception was: Mapper 'Mapper[Reserva(reserva)]' has no property 'finalizacao'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
	
2025-08-21 09:29:21,340 - INFO - GET ALL - Listagem de Responsaveis
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4255, in _do_configure_registries
	    mapper._post_configure_properties()
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2418, in _post_configure_properties
	    prop.init()
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
	    self.do_init()
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1661, in do_init
	    self._generate_backref()
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2145, in _generate_backref
	    self._add_reverse_property(self.back_populates)
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1592, in _add_reverse_property
	    other = self.mapper.get_property(key, _configure_mappers=False)
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2524, in get_property
	    raise sa_exc.InvalidRequestError(
	sqlalchemy.exc.InvalidRequestError: Mapper 'Mapper[Reserva(reserva)]' has no property 'finalizacao'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
	
2025-08-21 09:33:35,994 - INFO - GET ALL - Listagem de Responsaveis
2025-08-21 09:33:36,017 - INFO - Responsaveis retornadas com sucesso
2025-08-21 09:33:46,287 - INFO - GET ALL - Listagem de Finalizações